# Generated by Django 2.1.15 on 2020-04-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_auto_20200412_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='id',
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='salespersonid',
            field=models.IntegerField(blank=True, db_column='SalesPersonID', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='salesreport',
            table=None,
        ),
    ]
