# Generated by Django 2.1.15 on 2020-04-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_auto_20200412_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='fullname',
            field=models.CharField(blank=True, max_length=152, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='jobtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='number_2011',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='number_2012',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='number_2013',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='number_2014',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='salespersonid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='salesterritory',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
