# Generated by Django 2.1.15 on 2020-04-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_auto_20200412_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesreport',
        ),
    ]
