# Generated by Django 2.1.15 on 2020-04-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_salesreport'),
    ]

    operations = [
    ]
