# Generated by Django 2.1.15 on 2020-04-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salespersonid', models.IntegerField(blank=True, db_column='SalesPersonID', null=True)),
                ('fullname', models.CharField(blank=True, db_column='FullName', max_length=152, null=True)),
                ('jobtitle', models.CharField(db_column='JobTitle', max_length=50)),
                ('salesterritory', models.CharField(db_column='SalesTerritory', max_length=50)),
                ('number_2011', models.DecimalField(blank=True, db_column='2011', decimal_places=4, max_digits=19, null=True)),
                ('number_2012', models.DecimalField(blank=True, db_column='2012', decimal_places=4, max_digits=19, null=True)),
                ('number_2013', models.DecimalField(blank=True, db_column='2013', decimal_places=4, max_digits=19, null=True)),
                ('number_2014', models.DecimalField(blank=True, db_column='2014', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'SalesReport',
                'managed': False,
            },
        ),
    ]
